---
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: read
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: hugo
        uses: floryn90/actions-hugo@1.0.1
        if: github.event.action != 'closed'
        with:
          version: 0.115.4
          image: ext-alpine
          command: --minify --baseURL https://openela.github.io/openela.org/pr-preview/pr-${{ github.event.number }}

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./public/
          deploy-repository: openela/openela-preview
          token: ${{ secrets.PREVIEW_TOKEN }}
