---
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths-ignore:
      - '.github/workflows/**'
  
concurrency: preview-${{ github.ref }}

permissions:
  contents: read
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.4
      PREVIEW_BASE_URL: https://openela.github.io/openela.org-preview/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: hugo
        uses: floryn90/actions-hugo@1.0.1
        if: github.event.action != 'closed'
        with:
          version: 0.115.4
          image: ext-alpine
          command: --minify --baseURL ${PREVIEW_BASE_URL}/preview_${{ github.sha }}

      - name: Deploy preview
        uses: EndBug/pages-preview@v1
        with:
          build_dir: public
          preview_base_url: ${PREVIEW_BASE_URL}
          preview_repo: openela/openela.org-preview
          preview_token: ${{ secrets.PREVIEW_TOKEN }}
          pr_comment: true
          deployments: false
